### ISSUE TITLE
no consigo pasar parámetro en podcast

### ISSUE THREAD

**Issue by hayk99** [UNIZAR-30226-2020-01/frontend_flutter#26]
branch: dev_artistalbum
file: GenericNewPodcast
line: 136
Navigator.push(context, MaterialPageRoute(builder: (context) => PodcastChapterInfo(podcastChapter: this.podcastChapter,)));
mira a ver si sabes pq falla esto

**Comment by piter1902** [comment]
El fichero tenia el nombre mal
