### ISSUE TITLE
Comprobar si sigue funcionando vista detallada de album

### ISSUE THREAD

**Issue by jtambo99** [UNIZAR-30226-2020-01/frontend_flutter#36]
Se ha eliminado que en la vista detallada de álbum, para cada una de sus canciones aparezca información del álbum y por ende de su artista. (Se adjunta imagen de cómo se mostraba)
![Fallo_serializer_detailed_album2020-04-15 172917](https://user-images.githubusercontent.com/45767222/79355978-aae42600-7f3e-11ea-9283-ad56e82d74fc.png)

**Comment by piter1902** [comment]
Funciona correctamente.
